rename_map = {
    'Timestamp': 'timestamp',
    'Full name (as in your official documents)': 'full_name',
    'Email address': 'email',
    'Affiliation': 'affiliation',
    'Country of Citizenship': 'citizenship',
    'Gender': 'gender',
    'marks': 'marks',
    'Download the  zipped file "dsa-2026-notebook" , complete the exercises, and submit by uploading your zip file containing your notebook. Please follow the instructions carefully.\n': 'notebook_submission',
    'Current educational level or professional status ': 'education_level',
    'Field of study or expertise\n(e.g., Computer Science, Statistics, Engineering, Economics, GIS, Bioinformatics, etc.) ': 'field_of_study',
    'Institution/organization \n(University, research institute, company, or organization) ': 'institution',
    'Level of expertise in Machine Learning, Data science and AI': 'ml_expertise',
    'Briefly describe your motivation for attending the DSA 2026 Summer School (max 150 words) ': 'motivation',
    'How do you plan to apply the skills learned?': 'skill_application',
    'Please specify any 5 preferences from these topics below': 'topic_preferences',
    'Will you participate in the summer school, workshop, or both?': 'participation_type',
    'Do you have travel support?': 'travel_support',
    'Do you have any special needs or a disability that we should be aware of to support you better?': 'special_needs',
    'Country of Residence ': 'residence_country',
    'If yes, please briefly describe any accessibility or support needs we should consider (e.g., mobility, hearing, vision, dietary, learning support, or other): ': 'support_details',
    'Score': 'score',
    'Column 18': 'col_18',
    'Column 15': 'col_15',
    'Rate your knowledge of Python programming language': 'python_skill',
    'Rate your knowledge of using Jupyter notebook': 'jupyter_skill',
    'SECTION 2: Academic & Professional Background': 'section_2'
}